CREATE TABLE IF NOT EXISTS alembic_version (
    version_num VARCHAR(32) NOT NULL PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS "user" (
    id SERIAL PRIMARY KEY,
    token VARCHAR(2048),
    google_id VARCHAR(256) UNIQUE,
    facebook_id VARCHAR(256) UNIQUE,
    analytics_id VARCHAR(512),
    name VARCHAR(120),
    email VARCHAR(120),
    picture VARCHAR(512),
    last_seen TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS category (
    id SERIAL PRIMARY KEY,
    name VARCHAR(256) NOT NULL UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    slug VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS playlist (
    id SERIAL PRIMARY KEY,
    playlist_id VARCHAR(50) NOT NULL UNIQUE,
    channel_id VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(256) NOT NULL,
    channel_title VARCHAR(256),
    thumbnails BYTEA NOT NULL,
    channel_thumbnails BYTEA NOT NULL,
    description TEXT,
    channel_description TEXT,
    user_id INTEGER REFERENCES "user"(id),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS post (
    id SERIAL PRIMARY KEY,
    provider VARCHAR(7),
    video_id VARCHAR(20) NOT NULL UNIQUE,
    playlist_id VARCHAR(50),
    title VARCHAR(256) NOT NULL,
    thumbnails BYTEA NOT NULL,
    description TEXT,
    short_description TEXT,
    tags TEXT,
    duration VARCHAR(20) NOT NULL,
    upload_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "similar" BYTEA,
    user_id INTEGER REFERENCES "user"(id),
    playlist_db_id INTEGER REFERENCES playlist(id),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    category_id INTEGER REFERENCES category(id)
);


CREATE TABLE IF NOT EXISTS deleted_post (
    id SERIAL PRIMARY KEY,
    provider VARCHAR(7),
    video_id VARCHAR(20) NOT NULL UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS post_fave (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "user"(id),
    post_id INTEGER REFERENCES post(id),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS post_like (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "user"(id),
    post_id INTEGER REFERENCES post(id),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS page (
    id SERIAL PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    content TEXT,
    slug VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
